package main

import (
	"flag"
	"fmt"
	"go_neural_network/internal/irisnn"
	"log"
	"time"
)

// NeuralNetwork stores the trainable parameters for a simple
// single-hidden-layer classifier.

func main() {
	// Load the preprocessed CSV files generated by train_test_split.go.
	trainSet, err := irisnn.LoadDataset("train.csv")
	if err != nil {
		log.Fatal(err)
	}
	validationSet, err := irisnn.LoadDataset("validation.csv")
	if err != nil {
		log.Fatal(err)
	}
	testSet, err := irisnn.LoadDataset("test.csv")
	if err != nil {
		log.Fatal(err)
	}

	//take mean and std of individual sets or big set?
	scaler := irisnn.FitFeatureScaler(trainSet.Inputs)

	trainSet.Inputs = scaler.Transform(trainSet.Inputs)
	validationSet.Inputs = scaler.Transform(validationSet.Inputs)
	testSet.Inputs = scaler.Transform(testSet.Inputs)

	//init flags for modifying config

	modelOut := flag.String("model-out", "model.json", "Path to save the output model artifact")
	epochs := flag.Int("epochs", 100, "number of training interations")
	learningRate := flag.Float64("learning-rate", 0.15, "step size for updating weights")
	hiddenNeurons := flag.Int("hidden-neurons", 10, "number of neurons in the hidden layer")
	seed := flag.Int("seed", 42, "random seed for reproducible results")

	flag.Parse() //flag.Parse()

	var config irisnn.NeuralNetConfig

	config = irisnn.NeuralNetConfig{
		InputNeurons:  4,
		OutputNeurons: 3,
		HiddenNeurons: *hiddenNeurons,
		NumEpochs:     *epochs,
		LearningRate:  *learningRate,
		Seed:          *seed,
	}
	// A small hidden layer is enough for the Iris dataset.
	fmt.Printf("Training will run for %d epochs with a learning rate of %f\n", *epochs, *learningRate)

	network := irisnn.NewNeuralNetwork(config, scaler)

	fmt.Println("Training network...")
	startTime := time.Now()

	if err := network.Train(trainSet.Inputs, trainSet.Labels); err != nil {
		log.Fatal(err)
	}

	trainingDuration := time.Since(startTime)
	fmt.Printf("Training completed in %v\n\n", trainingDuration)

	// Report performance on all three splits so training quality is easy to inspect.
	trainLoss, trainAcc := irisnn.EvaluateSplit("Train", network, trainSet)
	valLoss, valAcc := irisnn.EvaluateSplit("Validation", network, validationSet)
	testLoss, testAcc := irisnn.EvaluateSplit("Test", network, testSet)

	metrics := irisnn.EvaluationMetrics{
		TrainLoss: trainLoss,
		ValLoss:   valLoss,
		TestLoss:  testLoss,
		TrainAcc:  trainAcc,
		ValAcc:    valAcc,
		TestAcc:   testAcc,
		Duration:  trainingDuration,
		Timestamp: time.Now(),
	}

	err = network.SavePreTrainedModel(*modelOut, metrics)
	if err != nil {
		log.Fatalf("Failed to save model artifact to %s: %v", *modelOut, err)
	}

	fmt.Printf("\nSuccess! Model saved to %s\n", *modelOut)
}
